alias npmpublic="npm config set registry https://registry.npmjs.org/"
alias npmprivate="npm config set registry http://npm.dev.wixpress.com"
alias mysql-start="brew services start mysql"
alias mysql-stop="brew services stop mysql"
alias wtf="rm -rf node_modules && rm -f package-lock.json && npm i"
alias taviuuid="echo f5fbc906-ff49-4d22-ab7e-d5a5960769fb | pbcopy"
alias yalla="npm start"
alias ten="npm run "
